### PR TITLE
no need to initiate the session in the test

### PR DESCRIPTION
**Pull request by christian-bromann**
Hi,

thanks for putting out that example project. I have a little improvement for you. You don't need to initialise an extra instance since the wdio runner does that for you (including shutting down the session).

### CODE REVIEW

**Comment by fand** [comment]
> the wdio runner does that for you (including shutting down the session)

Oh I missed it while reading docs :astonished: 
Thanks for advice!

**Comment by fand** [comment]
If we want multiple browsers in 1 test file, still we need launch browsers manually:

[https://gist.github.com/fand/6060e0599df64af40015#file-initmanually-js]

or, using `multiremote`: 

https://gist.github.com/fand/6060e0599df64af40015#file-multiremote-js

Is this correct? @christian-bromann

**Comment by christian-bromann** [comment]
no, just define multiple capabilities in your config file
https://github.com/webdriverio/webdriverio/blob/master/examples/wdio.cucumber.conf.js#L23-L29

**Comment by fand** [comment]
What I wanted was to test components which have diffrent behaviors for each browsers because of browser specific features e.g. `Object.observe`, in 1 test file.

Now I noticed that I can specify `specs` or `exclude` in wdio.conf.js and it's smarter than the way I wrote above.

Thanks a lot!

**Pull request merged**
